# Generated by Django 4.0.3 on 2022-03-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_propertybook_childern_alter_propertybook_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
